### ISSUE TITLE
On retrieving locale

### ISSUE THREAD

**Issue by myst729** [Jocs/jo-i18n#1]
https://github.com/Jocs/jo-i18n/blob/master/src/index.js#L8-L12

The DOM query part could be neater, in one line:

```js
const langMeta = document.querySelector('meta[http-equiv="content-language"]')
```

Another advantage, comparing to your original approach, it's case insensitive. Following markup will not work with `m.getAttribute('http-equiv') === 'Content-Language'`.

```html
<meta http-equiv="content-language" content="de">
```

On the other hand, the `<meta>` element is considered [bad practice](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language#Indicating_the_language_a_document_is_written_in) now. The new fashion is `lang` attribute of `<html>` element:

```html
<html lang="zh-CN">
```

This could be retrieved via `document.documentElement.lang` as well.

**Comment by Jocs** [comment]
@myst729 good suggestion. I will add the retrieving locale from html tag. 3q
